name: Build Binaries

on:
  workflow_dispatch:
  push:
    branches:
    - '**'              # every branch
    - '!no-build-**'    # unless marked as no-build

env:
  GEODE_CI: ''
  CCACHE_ACTION_CI: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          id: win
          extra_flags: -T host=x64 -A win32 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGEODE_DEBUG=On
          # uncomment to use vs clang-cl and ninja
          #extra_flags: >
          #  --no-warn-unused-cli
          #  "-DCMAKE_C_COMPILER:FILEPATH=$env:VCINSTALLDIR\Tools\Llvm\bin\clang-cl.exe"
          #  "-DCMAKE_CXX_COMPILER:FILEPATH=$env:VCINSTALLDIR\Tools\Llvm\bin\clang-cl.exe"
          #  -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGEODE_DEBUG=On
          cli_cmd: ''
          package_cmd: 'makensis -WX -V3 ./installer/windows/installer.nsi'
          installer_path: './installer/windows/geode-installer-win.exe'

        - name: macOS
          os: macos-latest
          id: mac
          extra_flags: >
            -DCMAKE_C_COMPILER=clang
            -DCMAKE_CXX_COMPILER=clang++
            -DCMAKE_C_COMPILER_LAUNCHER=ccache
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
            -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGEODE_DEBUG=On -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13
          cli_cmd: 'chmod +x $GITHUB_WORKSPACE/cli/geode'
          package_cmd: './installer/mac/package.sh ./bin/nightly ./installer/mac/geode-installer-mac.pkg'
          installer_path: './installer/mac/geode-installer-mac.pkg'

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ matrix.config.os }}
      if: matrix.config.id == 'mac'

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1.12.1
      with:
        arch: amd64_x86
      if: matrix.config.id == 'win'

    - name: Download CLI
      uses: robinraju/release-downloader@v1.8
      with:
        repository: geode-sdk/cli
        latest: true
        fileName: '*-${{ matrix.config.id }}.zip'
        tarBall: false
        zipBall: false
        out-file-path: "cli"

    - name: Setup CLI
      run: |
        7z x "${{ github.workspace }}/cli/*-${{ matrix.config.id }}.zip" -o"${{ github.workspace }}/cli"
        ${{ matrix.config.cli_cmd }}
        echo "${{ github.workspace }}/cli" >> $GITHUB_PATH

    #- name: Configure
    #  run: >
    #    cmake -B ${{ github.workspace }}/build
    #    -DCLI_PATH="${{ github.workspace }}/cli"
    #    ${{ matrix.config.extra_flags }}

    #- name: Build
    #  run: |
    #    cd ${{ github.workspace }}/build
    #    cmake --build . --config RelWithDebInfo --parallel
    #    rm ${{ github.workspace }}/bin/nightly/resources/.geode_cache

    - name: fake build mac
      shell: bash
      run: |
        mkdir -p ./bin/nightly/resources
        touch ./bin/nightly/resources/fake-resource.txt
        touch ./bin/nightly/Geode.dylib
        touch ./bin/nightly/GeodeBootstrapper.dylib
        touch ./bin/nightly/libfmod.dylib
      if: matrix.config.id == 'mac'

    - name: fake build win
      shell: bash
      run: |
        mkdir -p ./bin/nightly/resources
        touch ./bin/nightly/resources/fake-resource.txt
        touch ./bin/nightly/Geode.dll
        touch ./bin/nightly/Geode.pdb
        touch ./bin/nightly/Geode.lib
        touch ./bin/nightly/GeodeUpdater.exe
      if: matrix.config.id == 'win'

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: geode-${{ matrix.config.id }}
        path: ./bin/nightly

    - name: Package Installer
      run: ${{ matrix.config.package_cmd }}

    - name: Upload Installer
      uses: actions/upload-artifact@v3
      with:
        name: geode-installer-${{ matrix.config.id }}
        path: ${{ matrix.config.installer_path }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/resources-fix'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Declare Version Variables
        id: ref
        shell: bash
        run: |
          echo "version=$(cat ${{ github.workspace }}/VERSION | xargs)" >> $GITHUB_OUTPUT
          echo "hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}

      - name: Move Files
        run: |
          mv geode-installer-mac/geode-installer-mac.pkg geode-installer-${{ steps.ref.outputs.hash }}-mac.pkg
          mv geode-installer-win/geode-installer-win.exe geode-installer-${{ steps.ref.outputs.hash }}-win.exe
          mkdir -p geode-mac/geode/resources/geode.loader
          mkdir -p geode-win/geode/resources/geode.loader
          mv geode-mac/resources geode-mac/geode/resources/geode.loader
          mv geode-win/resources geode-win/geode/resources/geode.loader

      - name: Zip MacOS Artifacts
        uses: vimtor/action-zip@v1.1
        with:
          files: geode-mac/
          recursive: false
          dest: geode-${{ steps.ref.outputs.hash }}-mac.zip

      - name: Zip Windows Artifacts
        uses: vimtor/action-zip@v1.1
        with:
          files: geode-win/
          recursive: false
          dest: geode-${{ steps.ref.outputs.hash }}-win.zip

      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-test
          name: 'Dev Release'
          draft: true
          prerelease: true
          body: |
            Geode dev release for commit ${{ github.sha }}. Since this is not a regular release, Geode will not install the resources automatically, so you should use the installer if you want them.
          files: |
            ./geode-${{ steps.ref.outputs.hash }}-mac.zip
            ./geode-${{ steps.ref.outputs.hash }}-win.zip
            ./geode-installer-${{ steps.ref.outputs.hash }}-mac.pkg
            ./geode-installer-${{ steps.ref.outputs.hash }}-win.exe
